---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtnodelabellerbundles.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtNodeLabellerBundle
    listKind: KubevirtNodeLabellerBundleList
    plural: kubevirtnodelabellerbundles
    singular: kubevirtnodelabellerbundle
  scope: Namespaced
  version: v1
  subresources:
    status: {}

