---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kubevirtmetricsaggregations.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KubevirtMetricsAggregation
    listKind: KubevirtMetricsAggregationList
    plural: kubevirtmetricsaggregations
    singular: kubevirtmetricsaggregation
  scope: Namespaced
  version: v1
  subresources:
    status: {}

