---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: v2vvmwares.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: V2VVmware
    listKind: V2VVmwareList
    plural: v2vvmwares
    singular: v2vvmware
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
