if: type != pull_request OR branch =~ /^(release-[0-9\.]+)$/

language: generic
dist: xenial

services:
- docker

arch:
- amd64
# - ppc64le # temporary disable until we have it under control again

os: linux

install:
- git reset --hard

script:
- ./automation/travisci-test.sh

deploy:
- provider: script
  script: docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io && DOCKER_PREFIX="quay.io/kubevirt"
    DOCKER_TAG="$TRAVIS_TAG" QUAY_REPOSITORY="kubevirt" PACKAGE_NAME="kubevirt-operatorhub"
    sh -c 'make bazel-push-images && make manifests'
  skip_cleanup: true
  file:
  on:
    tags: true
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  script: make build-functests
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: releases
  skip_cleanup: true
  api_key:
    secure: KD1d1EkvX5iY5pvKQbi6Aj6y49XXnQBxBMok9x2d9LVMbmzBQIHoTqUQz2Dv2TSpANshkIrLmR1eT/brCK382cIUVvA6kG8JB2yqAAE2hzJ8u49+CI4iyqpBWw1HCuH/4xPWZUPVBW0Yl9WsW0vencAeKK6cTDm4Z9K3esJf+iZMpJh7ZpK2ESn9d2RZsrpOKJpxYrvt14Wox+8YfqPRCTJoO/Q8vdXbyOrRVpK6daSe11HsmTZZpFzgLWGojpjH05wcENUaokpCIp8Hgx3rJmO9z5iReNG+2QuPCw0QyEIKGAvzlA5KbYFWBUurxz0XsnaovbJ7BKI070arxQKjKRnjSNE3kEValOwMIE8dA835A1nChm85NILQdWvlbexSxPpz0z62SGPjFthUj9VBx/RnUrd1itxWOi6ZW5k6PnWDUoKPr63+fYSAkp6bXO9ELexA19wUfQCicGRBEO3mJ6QvKKbiDAFKWcABlavxlNtFgw1mMPxxWEhKkW0PrCqOVu9fDDzJ48DCD5XHRT8HUVHDeKcscMTW675rlzo3SxTJdqnZSybpbMSmKbxNs0rM8kPXf1RQLsGDg4CC6Daxz255PV5Y/+p0AhZ2hWtfC3c/Ff8wOdDSdCaEcg5tGa/e1kJWAKuIATUGdZsFZUri8ePQcgcXzM4ihANn7gP8Cl4=
  file_glob: true
  file:
  - _out/cmd/virtctl/virtctl-v*
  - _out/manifests/release/demo-content.yaml
  - _out/manifests/release/kubevirt-operator.yaml
  - _out/manifests/release/kubevirt-cr.yaml
  - _out/templates/manifests/release/kubevirt-operator.yaml.j2
  - _out/templates/manifests/release/kubevirt-cr.yaml.j2
  - _out/manifests/release/olm/kubevirt-operatorsource.yaml
  - _out/manifests/release/olm/bundle/kubevirtoperator.$TRAVIS_TAG.clusterserviceversion.yaml
  - _out/tests/tests.test
  - _out/manifests/release/conformance.yaml
  - _out/manifests/release/conformance.yaml.j2
  prerelease: true
  overwrite: true
  name: $TRAVIS_TAG
  on:
    tags: true
    repo: kubevirt/kubevirt
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  skip_cleanup: true
  script: bash hack/gen-swagger-doc/deploy.sh
  on:
    tags: true
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  skip_cleanup: true
  script: bash hack/gen-client-python/deploy.sh
  on:
    branch: master
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  skip_cleanup: true
  script: hack/publish-staging.sh
  on:
    tags: true
    condition: $TRAVIS_CPU_ARCH = amd64
- provider: script
  skip_cleanup: true
  script: hack/publish-staging.sh
  on:
    branch: master
    condition: $TRAVIS_CPU_ARCH = amd64
env:
  global:
  # api-reference token
  - secure: pS1N+T7f20B9PJ2S6e4Bc0z0vK6wnUgtGrs1982iXYocVZZtL6LreXYV/9a5ANrykLx+/qeRxbR4FTknfJwsmm2MX1WN7FIEtp7wGxt5uU0Q+b5pERbgUL8amkvhc6Hj9eWn59fbEKSmAEeMupeYydPPCFJp8oumEEP6szb0zCj7LQPWxhEMtVLY2U8d3WbkhBoxC1Bv5kTOajaiyuwjgiJd3yvR6WfNOQUL167TCoyzRDoe7jUSZ9EScyDRg7mC2Nk2o4vzZwmaz8QjO6T6f2za95t7/kxhYrL7WAfa3POxdhHPP0XX4ZsypU6++hDj0txPAB/ICa55Za6A+BhFrUdGeoYb3T8jtWIF9UDHq6m8yhurtDPooR7VMjkR2ghz4Ol4cv2f1QWv5MGDg4hh9gKgjE+gbbeZyA5+t3l/Zf2HozZQCIDpMpi4EUUS3rCGkr44h0AjiZP9s4QrUY74kpT6GEGluFTlkXar+R3bvnTVY2J4vj6XGdAXHYtAbKI2/yaq20wqkbsC6BKHITcZ/E3eIBh2kc0WD4pdm8MnI0chuuMSkM6ynRDcPNYi235VmhxuUBaNWrkQEHGVOjXJPLB+xMRc6vVxAjV/OFaKXsbPb4aJl1TRJ1RclHAf4Am3SPuiowm8JmODTrmmYkF67rAGILO1oVxwmvwVLAmcJSI=
  # QUAY_USERNAME
  - secure: "rWM5uf1pMw+s+19YfzPgr/iT0j9o50eR1NPCLR7lkZhXMtNMxE8I3XOhapMXHHcTQ/kyxvaRzO48Q1SeVOK5QkI47YG4y6Zmyg/tGiUyymYHsaXk3a1GIB9f7J+oRTv5wZLx25Ss/JMMWuL5B74I57iFkqWE8EClvr8UZ6TqYniVLXdD9VPcYL1wkVHjkEyHg75PAR6U31SRSgQtDVQq6BHVGnjLWM+JfKcg4G+J90CxHbFyOJXfYw+HjP74ZDIKViu06SfZZV1zEecmf9xweYFo+dQpFXUMacMskVxcEfe1Qv9PE/H6XLJJ2pYz7g+Xviuy1CSdpo7Wmic4b8VkSxckKGXoH9GsW/PLSobVCcjAPi4hlZfxCjUXZsESVXEnipti7bUDbdCHDQ3Yffaa6BoIkOAs59DWnoBlgd9D7rPq9aRPxrSs3e+VYviKNgTKDnYJR7IDtzS1l9ebdczEHOdFMaCWZvEOFh4IbnkTZHecnknih2EMRaycEsB53IXgCx519ofQy9EdPwJLNrCvcTyeiyIc0PQYjfr41wEeGxuTMNbePLRr2DOGdNvieSzmJTlPyuMFa7Rc0alUsULUJDOT2Yjw56ybGOnatz3XtPZYpszYDSBP6QSV3mInCFglZqP0iloddcKCSDRKDm/lYCvKC6ltPI6wvF6BLZoslwo="
  # QUAY_PASSWORD
  - secure: "Hq/NJhkWh1G7q0Rxwl+w+sqyugSrGx+nVBPB3JjI2oxksQAc6AgAniJf/xpMTs1EZD0e5cOkXVsYeTpkFa062Y8MoM/8+VElUGbgL5VoI1/JxtMW8eXKpQiLaXi5BiEJwa17cCvLEXWb5rDFXLcbxLYiAv2QAMrOY3D6SOMxBYRvrHc1tDxukk2RUaCP8I+ROsUxyxDxItIOxJEDvOAV6+x25i6WYKmdgmudJUaWkifzyOoioiiJVLdmYD49hYQddywCCc63ut07rYsG6jJL7Q0o35ko+x1nFfXNFYI1ESfcuwZy7/ZuitJRCgh/8J9LCLOdXiWwkukX/RJAe9Z72zM3RgG13eGZQC5Mr46bYCepRp3wh1IuRaThGsJUZdSXOVnlpFK1vwikfrZo5mYhPNGIMEk2E46wsyIKkZmyAkuo3agUb/VdKumUk+c+Cw29oifOHXoPtTqqc4b3H4lkbdYa174d6wf19OudHaa3SyX/+LcyugCpswefsVa/vZExJKvYZdG9r5XIF2vk4DRS1iZKp//7oojzS1Rlxub0PtpqH8Sruzk4D+ocAHjirHyP6PNYaHvmugguuJ+RlR1eDm83lzAllqn9YBMJJ+q50Z8TUX1U4RsRsfj0L3YuIFdS011+4GDrxaz90UCLa3l1gyW5dyd8jC6yaeCDHIYT+pE="

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always
