apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hco-operatorhub
spec:
  source: kubevirt-hyperconverged
  sourceNamespace: openshift-marketplace
  name: community-kubevirt-hyperconverged
  #startingCSV: kubevirt-hyperconverged-operator.v1.7.0
  channel: "1.7.0"
