apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/kubevirt/hyperconverged-cluster-index:1.10.0-unstable
  displayName: KubeVirt HyperConverged
  publisher: KubeVirt Project
