---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: hyperconverged-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperconverged-cluster-operator
subjects:
- kind: ServiceAccount
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: cdi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator
subjects:
- kind: ServiceAccount
  name: cdi-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cdi-operator-admin
  labels:
    operator.kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cdi-operator
    namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    kubevirt.io: ""
  name: cluster-network-addons-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-network-addons-operator
subjects:
  - kind: ServiceAccount
    name: cluster-network-addons-operator
    namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-network-addons-operator-admin
  labels:
    operator.kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cluster-network-addons-operator
    namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-ssp-operator
  labels:
    operator.kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: kubevirt-ssp-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubevirt-ssp-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-web-ui-operator
  labels:
    operator.kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: kubevirt-web-ui-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubevirt-web-ui-operator
    namespace: kubevirt-hyperconverged
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-maintenance-operator
roleRef:
  kind: ClusterRole
  name: node-maintenance-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: node-maintenance-operator
  namespace: kubevirt-hyperconverged
