apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kwebuis.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: KWebUI
    listKind: KWebUIList
    plural: kwebuis
    singular: kwebui
  scope: Namespaced
  version: v1alpha1
