---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    name: cluster-network-addons-operator
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-network-addons-operator
subjects:
- kind: ServiceAccount
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: hyperconverged-cluster-operator
  name: hyperconverged-cluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperconverged-cluster-operator
subjects:
- kind: ServiceAccount
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: cluster-network-addons-operator
  name: cluster-network-addons-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-network-addons-operator
subjects:
- kind: ServiceAccount
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: kubevirt-operator
  name: kubevirt-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: kubevirt-ssp-operator
  name: kubevirt-ssp-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-ssp-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-ssp-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: cdi-operator
  name: cdi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi-operator
subjects:
- kind: ServiceAccount
  name: cdi-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: node-maintenance-operator
  name: node-maintenance-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-maintenance-operator
subjects:
- kind: ServiceAccount
  name: node-maintenance-operator
  namespace: kubevirt-hyperconverged
