---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: cdi-operator
  name: cdi-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: cluster-network-addons-operator
  name: cluster-network-addons-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: hostpath-provisioner-operator
  name: hostpath-provisioner-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: hyperconverged-cluster-operator
  name: hyperconverged-cluster-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: kubevirt-operator
  name: kubevirt-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: node-maintenance-operator
  name: node-maintenance-operator
  namespace: kubevirt-hyperconverged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: ssp-operator
  name: ssp-operator
  namespace: kubevirt-hyperconverged
