---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachineinstancemigrations.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: VirtualMachineInstanceMigration
    plural: virtualmachineinstancemigrations
    shortNames:
    - vmim
    - vmims
    singular: virtualmachineinstancemigration
  scope: Namespaced
  version: v1alpha3
