---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachineinstancepresets.kubevirt.io
spec:
  group: kubevirt.io
  names:
    kind: VirtualMachineInstancePreset
    plural: virtualmachineinstancepresets
    shortNames:
    - vmipreset
    - vmipresets
    singular: virtualmachineinstancepreset
  scope: Namespaced
  version: v1alpha2
