---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachineinstancereplicasets.kubevirt.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.replicas
    description: Number of desired VirtualMachineInstances
    name: Desired
    type: integer
  - JSONPath: .status.replicas
    description: Number of managed and not final or deleted VirtualMachineInstances
    name: Current
    type: integer
  - JSONPath: .status.readyReplicas
    description: Number of managed VirtualMachineInstances which are ready to receive
      traffic
    name: Ready
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: kubevirt.io
  names:
    kind: VirtualMachineInstanceReplicaSet
    plural: virtualmachineinstancereplicasets
    shortNames:
    - vmirs
    - vmirss
    singular: virtualmachineinstancereplicaset
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.labelSelector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
  version: v1alpha2
