Schema: olm.semver
GenerateMajorChannels: false
GenerateMinorChannels: true
DefaultChannelTypePreference: minor
Candidate:
  Bundles:
    - Image: quay.io/kubevirt/hyperconverged-cluster-bundle:1.16.0
