packageName: community-kubevirt-hyperconverged
channels:
- name: "1.7.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.7.0
- name: "1.6.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.6.0
- name: "1.5.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.5.0
- name: "1.4.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.4.0
- name: "1.3.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.3.0
- name: "1.2.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.2.0
- name: "1.1.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.1.0
- name: "1.0.0"
  currentCSV: kubevirt-hyperconverged-operator.v1.0.0
- name: "0.0.3"
  currentCSV: kubevirt-hyperconverged-operator.v0.0.3
- name: "0.0.2"
  currentCSV: kubevirt-hyperconverged-operator.v0.0.2
- name: "0.0.1"
  currentCSV: kubevirt-hyperconverged-operator.v0.0.1
defaultChannel: "1.7.0"
