name: Rebase Bot
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Build Manifests and Rebase
    if: (github.event.issue.pull_request != '') && (contains(github.event.comment.body, '/rebase')) && (github.repository == 'kubevirt/hyperconverged-cluster-operator')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.HCO_BOT_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build Manifests and Rebase
        run: ./automation/rebase-bot/rebase-bot.sh
        env:
          GITHUB_TOKEN: ${{ secrets.HCO_BOT_TOKEN }}