name: Auto-Bump Component's Versions
on:
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:
jobs:
  build:
    name: HCO Release Bump Job
    if: (github.repository == 'kubevirt/hyperconverged-cluster-operator')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.

      - name: Check for new releases and update
        run: |
          ./automation/release-bumper/release-bumper.sh
          if [[ -f updated_component.txt ]]; then
            echo 'UPDATED_COMPONENT<<EOF' >> $GITHUB_ENV
            cat updated_component.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            UPDATED_COMPONENT_EXISTS=true
          fi

          if [[ -f updated_version.txt ]]; then
            echo 'UPDATED_VERSION<<EOF' >> $GITHUB_ENV
            cat updated_version.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            UPDATED_VERSION_EXISTS=true
          fi

          if [[ -n ${UPDATED_COMPONENT_EXISTS} && -n ${UPDATED_VERSION_EXISTS} ]]; then
            echo "CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Remove temporary files
        if: ${{ env.CHANGED }}
        run: rm -f updated_component.txt updated_version.txt

      - uses: peter-evans/create-pull-request@v3
        if: ${{ env.CHANGED }}
        with:
          token: ${{ secrets.HCO_BOT_TOKEN }}
          commit-message: |
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}

            Signed-off-by: HCO Bump Bot <noreply@github.com>
          committer: HCO Bump Bot <noreply@github.com>
          title: "Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}"
          body: |
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}
            Executed by HCO Release-Bumper Bot.
            ```release-note
            Bump ${{ env.UPDATED_COMPONENT }} to ${{ env.UPDATED_VERSION }}
            ```
          assignees: tiraboschi,orenc1,nunnatsa
          reviewers: tiraboschi,orenc1,nunnatsa
          team-reviewers: owners, maintainers
          branch: bump_${{ env.UPDATED_COMPONENT }}_${{ env.UPDATED_VERSION }}
